import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { CoverLetterService } from '../../services/cover-letter.service';
import { CoverLetterRecord, LlmResult, CoverLetterRequest } from '../../models/models';

@Component({
  selector: 'app-history',
  imports: [CommonModule],
  templateUrl: './history.component.html',
  styleUrl: './history.component.scss'
})
export class HistoryComponent implements OnInit {
  records = signal<CoverLetterRecord[]>([]);
  isLoading = signal(false);
  errorMessage = signal<string | null>(null);

  constructor(
    private coverLetterService: CoverLetterService,
    private router: Router
  ) {}

  ngOnInit() {
    this.loadHistory();
  }

  loadHistory() {
    this.isLoading.set(true);
    this.errorMessage.set(null);
    
    this.coverLetterService.history().subscribe({
      next: (data) => {
        // Sort history by date descending
        const sorted = (data || []).sort((a, b) => 
          new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
        );
        this.records.set(sorted);
        this.isLoading.set(false);
      },
      error: (err) => {
        console.error('Failed to load cover letter history:', err);
        this.errorMessage.set('Could not load cover letter history from server. Ensure Kestrel backend API is active.');
        this.isLoading.set(false);
      }
    });
  }

  // Load a historical record back into the active Preview state
  loadRecord(rec: CoverLetterRecord) {
    this.isLoading.set(true);

    // Reconstruct the request payload
    const request: CoverLetterRequest = {
      mode: 'existing',
      companyName: rec.companyName,
      position: rec.position,
      contactPerson: rec.contactPerson,
      department: rec.department,
      companyLocation: rec.companyLocation,
      language: rec.language,
      selectedTemplate: rec.selectedTemplate || 'template_1',
      coverLetterBody: rec.contentBody // Use history body as prompt
    };

    // Reconstruct LLM result layout from contentBody
    let parsedLayout;
    try {
      // If contentBody is stored as JSON in db (which it is for custom edits)
      parsedLayout = JSON.parse(rec.contentBody);
    } catch {
      // If it's stored as plain text, parse/reconstruct standard structure
      const paragraphs = rec.contentBody.split('\n\n')
        .map(p => p.trim())
        .filter(p => p.length > 0);

      let salutation = 'Dear Hiring Manager,';
      let signer = 'Sincerely,';
      let body = paragraphs;

      if (paragraphs.length > 0 && paragraphs[0].toLowerCase().startsWith('dear')) {
        salutation = paragraphs[0];
        body = paragraphs.slice(1);
      }
      if (body.length > 0 && (body[body.length - 1].toLowerCase().includes('regards') || body[body.length - 1].toLowerCase().includes('sincerely'))) {
        signer = body[body.length - 1];
        body = body.slice(0, body.length - 1);
      }

      parsedLayout = {
        salutationLine: salutation,
        bodyParagraphs: body,
        closingLine: 'Best regards,',
        signerName: signer
      };
    }

    // Call preview generation again to pull PDF base64 if needed, or build preview payload
    const mockResult: LlmResult = {
      layout: {
        companyNameFormatted: rec.companyName,
        positionFormatted: rec.position,
        salutationLine: parsedLayout.salutationLine || 'Dear Hiring Manager,',
        bodyParagraphs: parsedLayout.bodyParagraphs || [rec.contentBody],
        closingLine: parsedLayout.closingLine || 'Best regards,',
        signerName: parsedLayout.signerName || 'Applicant',
        companyLocation: rec.companyLocation || '',
        contactPerson: rec.contactPerson || '',
        department: rec.department || ''
      },
      wasFallback: rec.usedProvider === 'RawFallback',
      warnings: [],
      attemptLog: [`Loaded historical draft generated by ${rec.usedProvider} (${rec.usedModel})`],
      syncedToMcp: rec.syncedToMcp
    };

    // Trigger API preview to get the QuestPDF rendering for this historical state
    this.coverLetterService.preview(request).subscribe({
      next: (previewRes) => {
        this.coverLetterService.setPreviewData(previewRes, request, rec.language);
        this.coverLetterService.setComposeState(request);
        this.isLoading.set(false);
        this.router.navigate(['/preview']);
      },
      error: (err) => {
        // Fallback: load using mock result without PDF base64
        console.warn('Could not render PDF preview for history item, loading text-only context.', err);
        this.coverLetterService.setPreviewData(mockResult, request, rec.language);
        this.coverLetterService.setComposeState(request);
        this.isLoading.set(false);
        this.router.navigate(['/preview']);
      }
    });
  }

  formatDate(dateStr: string): string {
    if (!dateStr) return '';
    const date = new Date(dateStr);
    return date.toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }
}
