import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { forkJoin } from 'rxjs';
import { CoverLetterService } from '../../services/cover-letter.service';
import { ResumeService } from '../../services/resume.service';
import { CoverLetterRecord, ResumeRecord, LlmResult, CoverLetterRequest, ResumeRequest, ResumeResult } from '../../models/models';

export interface HistoryItem {
  id: number;
  docType: 'cover_letter' | 'resume';
  title: string;
  subtitle: string;
  language: string;
  usedProvider: string;
  usedModel: string;
  syncedToMcp: boolean;
  createdAt: string;
  rawRecord: CoverLetterRecord | ResumeRecord;
}

@Component({
  selector: 'app-history',
  imports: [CommonModule, RouterLink],
  templateUrl: './history.component.html',
  styleUrl: './history.component.scss'
})
export class HistoryComponent implements OnInit {
  records = signal<HistoryItem[]>([]);
  isLoading = signal(false);
  errorMessage = signal<string | null>(null);

  constructor(
    private coverLetterService: CoverLetterService,
    private resumeService: ResumeService,
    private router: Router
  ) {}

  ngOnInit() {
    this.loadHistory();
  }

  loadHistory() {
    this.isLoading.set(true);
    this.errorMessage.set(null);
    
    forkJoin({
      coverLetters: this.coverLetterService.history(),
      resumes: this.resumeService.history()
    }).subscribe({
      next: ({ coverLetters, resumes }) => {
        const clItems: HistoryItem[] = (coverLetters || []).map(c => ({
          id: c.id,
          docType: 'cover_letter',
          title: c.companyName || 'Cover Letter',
          subtitle: c.position || 'Position',
          language: c.language || 'en',
          usedProvider: c.usedProvider || 'fallback',
          usedModel: c.usedModel || 'none',
          syncedToMcp: c.syncedToMcp,
          createdAt: c.createdAt,
          rawRecord: c
        }));

        const resumeItems: HistoryItem[] = (resumes || []).map(r => ({
          id: r.id,
          docType: 'resume',
          title: 'Resume / CV',
          subtitle: r.summary ? r.summary.substring(0, 45) + '...' : 'Professional Resume',
          language: r.language || 'en',
          usedProvider: r.usedProvider || 'fallback',
          usedModel: r.usedModel || 'none',
          syncedToMcp: r.syncedToMcp,
          createdAt: r.createdAt,
          rawRecord: r
        }));

        const merged = [...clItems, ...resumeItems].sort((a, b) => 
          new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
        );

        this.records.set(merged);
        this.isLoading.set(false);
      },
      error: (err) => {
        console.error('Failed to load history:', err);
        this.errorMessage.set('Could not load generation history from server. Ensure backend API is active.');
        this.isLoading.set(false);
      }
    });
  }

  loadItem(item: HistoryItem) {
    this.isLoading.set(true);

    if (item.docType === 'resume') {
      const rec = item.rawRecord as ResumeRecord;
      const request: ResumeRequest = {
        summary: rec.summary || '',
        experience: rec.experience || '',
        education: rec.education || '',
        skills: rec.skills || '',
        projects: rec.projects || '',
        language: rec.language || 'en',
        selectedTemplate: rec.selectedTemplate || 'template_1',
        headerAddress: rec.headerAddress || ''
      };

      const mockResult: ResumeResult = {
        layout: {
          summaryFormatted: rec.summary || '',
          experienceFormatted: rec.experience || '',
          educationFormatted: rec.education || '',
          skillsFormatted: rec.skills || '',
          projectsFormatted: rec.projects || ''
        },
        wasFallback: rec.usedProvider === 'fallback',
        warnings: [],
        attemptLog: [`Loaded historical draft generated by ${rec.usedProvider} (${rec.usedModel})`],
        usedProvider: rec.usedProvider,
        usedModel: rec.usedModel
      };

      this.resumeService.preview(request).subscribe({
        next: (previewRes) => {
          this.resumeService.setPreviewData(previewRes, request, rec.language);
          this.resumeService.setResumeComposeState(request);
          this.isLoading.set(false);
          this.router.navigate(['/preview']);
        },
        error: () => {
          this.resumeService.setPreviewData(mockResult, request, rec.language);
          this.resumeService.setResumeComposeState(request);
          this.isLoading.set(false);
          this.router.navigate(['/preview']);
        }
      });
      return;
    }

    // Cover Letter load
    const rec = item.rawRecord as CoverLetterRecord;
    const request: CoverLetterRequest = {
      mode: 'existing',
      companyName: rec.companyName,
      position: rec.position,
      contactPerson: rec.contactPerson,
      department: rec.department,
      companyLocation: rec.companyLocation,
      language: rec.language,
      selectedTemplate: rec.selectedTemplate || 'template_1',
      coverLetterBody: rec.contentBody
    };

    let parsedLayout;
    try {
      parsedLayout = JSON.parse(rec.contentBody);
    } catch {
      const paragraphs = (rec.contentBody || '').split('\n\n')
        .map(p => p.trim())
        .filter(p => p.length > 0);

      let salutation = 'Dear Hiring Manager,';
      let signer = 'Sincerely,';
      let body = paragraphs;

      if (paragraphs.length > 0 && paragraphs[0].toLowerCase().startsWith('dear')) {
        salutation = paragraphs[0];
        body = paragraphs.slice(1);
      }
      if (body.length > 0 && (body[body.length - 1].toLowerCase().includes('regards') || body[body.length - 1].toLowerCase().includes('sincerely'))) {
        signer = body[body.length - 1];
        body = body.slice(0, body.length - 1);
      }

      parsedLayout = {
        salutationLine: salutation,
        bodyParagraphs: body,
        closingLine: 'Best regards,',
        signerName: signer
      };
    }

    const mockResult: LlmResult = {
      layout: {
        companyNameFormatted: rec.companyName,
        positionFormatted: rec.position,
        salutationLine: parsedLayout.salutationLine || 'Dear Hiring Manager,',
        bodyParagraphs: parsedLayout.bodyParagraphs || [rec.contentBody],
        closingLine: parsedLayout.closingLine || 'Best regards,',
        signerName: parsedLayout.signerName || 'Applicant',
        companyLocation: rec.companyLocation || '',
        contactPerson: rec.contactPerson || '',
        department: rec.department || ''
      },
      wasFallback: rec.usedProvider === 'RawFallback',
      warnings: [],
      attemptLog: [`Loaded historical draft generated by ${rec.usedProvider} (${rec.usedModel})`],
      syncedToMcp: rec.syncedToMcp
    };

    this.coverLetterService.preview(request).subscribe({
      next: (previewRes) => {
        this.coverLetterService.setPreviewData(previewRes, request, rec.language);
        this.coverLetterService.setComposeState(request);
        this.isLoading.set(false);
        this.router.navigate(['/preview']);
      },
      error: () => {
        this.coverLetterService.setPreviewData(mockResult, request, rec.language);
        this.coverLetterService.setComposeState(request);
        this.isLoading.set(false);
        this.router.navigate(['/preview']);
      }
    });
  }

  formatDate(dateStr: string): string {
    if (!dateStr) return '';
    const date = new Date(dateStr);
    return date.toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }
}

